<?php

namespace Database\Seeders;

use App\Models\Ticket;
use Illuminate\Database\Seeder;

class TicketTableSeeder extends Seeder
{
    public function run()
    {
        $ticket = [
            [
                'id'    => 1,
                'user_id'  => 13,
                'subject' => 'Cannot access e-mail',
                'description' => 'Cannot access e-mail',
                'admin_id' => 1,
                'category_id' => 5,
                'status_id' => 1,
                'priority_id' => 2,
                'ticket_file' => 'ticket_files/1_testing.txt',
                'created_at' => date("2022-01-01 13:15:00"),
                'updated_at' => date("2022-01-01 14:15:00"),
            ],
            [
                'id'    => 2,
                'user_id'  => 6,
                'subject' => 'No School Wi-Fi',
                'description' => 'No School Wi-Fi',
                'admin_id' => 14,
                'category_id' => 7,
                'status_id' => 1,
                'priority_id' => 3,
                'ticket_file' => 'ticket_files/2_testing.csv',
                'created_at' => date("2022-02-01 13:15:00"),
                'updated_at' => date("2022-02-01 15:15:00"),
            ],
            [
                'id'    => 3,
                'user_id'  => 12,
                'subject' => 'Cannot access e-mail',
                'description' => 'Cannot access e-mail',
                'admin_id' => 1,
                'category_id' => 5,
                'status_id' => 3,
                'priority_id' => 1,
                'ticket_file' => 'ticket_files/3_testing.png',
                'created_at' => date("2022-03-01 13:15:00"),
                'updated_at' => date("2022-03-01 16:15:00"),
            ],
            [
                'id'    => 4,
                'user_id'  => 6,
                'subject' => 'Cannot access AIMS',
                'description' => 'Cannot access AIMS',
                'admin_id' => 3,
                'category_id' => 3,
                'status_id' => 2,
                'priority_id' => 3,
                'ticket_file' => '',
                'created_at' => date("2022-03-15 13:15:00"),
                'updated_at' => date("2022-03-15 17:15:00"),
            ],
            [
                'id'    => 5,
                'user_id'  => 10,
                'subject' => 'Cannot access Panpacific Website',
                'description' => 'Cannot access Panpacific Website',
                'admin_id' => 1,
                'category_id' => 2,
                'status_id' => 1,
                'priority_id' => 1,
                'ticket_file' => '',
                'created_at' => date("2022-03-16 10:15:00"),
                'updated_at' => date("2022-03-16 11:15:00"),
            ],
            [
                'id'    => 6,
                'user_id'  => 9,
                'subject' => 'Cannot access AIMS',
                'description' => 'Cannot access AIMS',
                'admin_id' => 2,
                'category_id' => 3,
                'status_id' => 2,
                'priority_id' => 2,
                'ticket_file' => '',
                'created_at' => date("2022-03-23 07:15:00"),
                'updated_at' => date("2022-03-23 08:15:00"),
            ],
            [
                'id'    => 7,
                'user_id'  => 8,
                'subject' => 'Cannot access Google Classroom',
                'description' => 'Cannot access Google Classroom',
                'admin_id' => 3,
                'category_id' => 4,
                'status_id' => 3,
                'priority_id' => 3,
                'ticket_file' => '',
                'created_at' => date("2022-03-22 07:15:00"),
                'updated_at' => date("2022-03-22 08:15:00"),
            ],
            [
                'id'    => 8,
                'user_id'  => 7,
                'subject' => 'Cannot access e-mail',
                'description' => 'Cannot access e-mail',
                'admin_id' => 4,
                'category_id' => 5,
                'status_id' => 1,
                'priority_id' => 2,
                'ticket_file' => '',
                'created_at' => date("2022-03-23 07:15:00"),
                'updated_at' => date("2022-03-23 08:15:00"),
            ],
            [
                'id'    => 9,
                'user_id'  => 6,
                'subject' => 'PC frozen in Computer Lab',
                'description' => 'PC frozen in Computer Lab',
                'admin_id' => 5,
                'category_id' => 6,
                'status_id' => 2,
                'priority_id' => 3,
                'ticket_file' => '',
                'created_at' => date("2022-03-24 07:15:00"),
                'updated_at' => date("2022-03-26 02:15:00"),
            ],
            [
                'id'    => 10,
                'user_id'  => 13,
                'subject' => 'No Connection School Wi-Fi',
                'description' => 'No Connection School Wi-Fi',
                'admin_id' => 11,
                'category_id' => 7,
                'status_id' => 2,
                'priority_id' => 4,
                'ticket_file' => '',
                'created_at' => date("2022-03-25 07:15:00"),
                'updated_at' => date("2022-03-26 07:15:00"),
            ],
            [
                'id'    => 11,
                'user_id'  => 12,
                'subject' => 'Transcript of Record request',
                'description' => 'Transcript of Record request',
                'admin_id' => 14,
                'category_id' => 8,
                'status_id' => 1,
                'priority_id' => 1,
                'ticket_file' => '',
                'created_at' => date("2022-03-26 07:15:00"),
                'updated_at' => date("2022-03-27 07:15:00"),
            ],
            [
                'id'    => 12,
                'user_id'  => 8,
                'subject' => 'Cannot access Panpacific Website',
                'description' => 'Cannot access Panpacific Website',
                'admin_id' => 15,
                'category_id' =>2,
                'status_id' => 2,
                'priority_id' => 2,
                'ticket_file' => '',
                'created_at' => date("2022-03-27 07:15:00"),
                'updated_at' => date("2022-03-28 07:15:00"),
            ],
            [
                'id'    => 13,
                'user_id'  => 7,
                'subject' => 'No subject invitation Google Classroom',
                'description' => 'No subject invitation Google Classroom',
                'admin_id' => 2,
                'category_id' => 4,
                'status_id' => 3,
                'priority_id' => 4,
                'ticket_file' => '',
                'created_at' => date("2022-03-28 07:15:00"),
                'updated_at' => date("2022-03-28 08:15:00"),
            ],
            [
                'id'    => 14,
                'user_id'  =>10,
                'subject' => 'No Internet in Computer Lab',
                'description' => 'No Internet in Computer Lab',
                'admin_id' => 4,
                'category_id' => 6,
                'status_id' => 1,
                'priority_id' => 2,
                'ticket_file' => '',
                'created_at' => date("2022-03-28 08:15:00"),
                'updated_at' => date("2022-03-28 09:15:00"),
            ],
            [
                'id'    => 15,
                'user_id'  => 6,
                'subject' => 'Graduation Diploma',
                'description' => 'Graduation Diploma',
                'admin_id' => 14,
                'category_id' => 8,
                'status_id' => 1,
                'priority_id' => 3,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 01:15:00"),
                'updated_at' => date("2022-03-29 02:15:00"),
            ],
            [
                'id'    => 16,
                'user_id'  => 9,
                'subject' => 'Cannot view Registration Tab',
                'description' => 'Cannot view Registration Tab',
                'admin_id' => 15,
                'category_id' => 3,
                'status_id' => 2,
                'priority_id' => 2,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 02:15:00"),
                'updated_at' => date("2022-03-29 03:15:00"),
            ],
            [
                'id'    => 17,
                'user_id'  => 13,
                'subject' => 'Cannot send e-mail',
                'description' => 'Cannot send e-mail',
                'admin_id' => 11,
                'category_id' => 5,
                'status_id' => 3,
                'priority_id' => 1,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 03:15:00"),
                'updated_at' => date("2022-03-29 04:15:00"),
            ],
            [
                'id'    => 18,
                'user_id'  => 8,
                'subject' => 'Testing Uncategorized Selection',
                'description' => 'Testing Uncategorized Selection',
                'admin_id' => 5,
                'category_id' => 1,
                'status_id' => 1,
                'priority_id' => 3,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 04:15:00"),
                'updated_at' => date("2022-03-29 05:15:00"),
            ],
            [
                'id'    => 19,
                'user_id'  => 12,
                'subject' => 'Cannot view Accounts Tab',
                'description' => 'Cannot view Accounts Tab',
                'admin_id' => 3,
                'category_id' => 3,
                'status_id' => 2,
                'priority_id' => 2,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 05:15:00"),
                'updated_at' => date("2022-03-29 06:15:00"),
            ],
            [
                'id'    => 20,
                'user_id'  => 7,
                'subject' => 'Cannot access Panpacific Website',
                'description' => 'Cannot access Panpacific Website',
                'admin_id' => 1,
                'category_id' => 2,
                'status_id' => 1,
                'priority_id' => 1,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 06:15:00"),
                'updated_at' => date("2022-03-29 07:15:00"),
            ],
            [
                'id'    => 21,
                'user_id'  => 6,
                'subject' => 'No subject invite',
                'description' => 'No subject invite',
                'admin_id' => 3,
                'category_id' => 4,
                'status_id' => 3,
                'priority_id' => 3,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 07:15:00"),
                'updated_at' => date("2022-03-29 08:15:00"),
            ],
            [
                'id'    => 22,
                'user_id'  => 10,
                'subject' => 'Cannot receive e-mail',
                'description' => 'Cannot receive e-mail',
                'admin_id' => 2,
                'category_id' => 5,
                'status_id' => 1,
                'priority_id' => 2,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 08:15:00"),
                'updated_at' => date("2022-03-29 09:15:00"),
            ],
            [
                'id'    => 23,
                'user_id'  => 9,
                'subject' => 'Black Screen PC1 in Computer Lab',
                'description' => 'Black Screen PC1 in Computer Lab',
                'admin_id' => 1,
                'category_id' => 6,
                'status_id' => 2,
                'priority_id' => 3,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 09:15:00"),
                'updated_at' => date("2022-03-29 11:15:00"),
            ],
            [
                'id'    => 24,
                'user_id'  => 11,
                'subject' => 'Wrong Password School Wi-Fi',
                'description' => 'Wrong Password School Wi-Fi',
                'admin_id' => 5,
                'category_id' => 7,
                'status_id' => 2,
                'priority_id' => 4,
                'ticket_file' => '',
                'created_at' => date("2022-03-29 10:15:00"),
                'updated_at' => date("2022-03-29 12:15:00"),
            ],
        ];

        Ticket::insert($ticket);
    }
}
